fix: get network data using winapi
glzr-io/zebar pull request #125
Opened 2024-10-09 15:43 UTC by SebasF1349

Zebar was using `netsh` to get wifi data and then parse it using regex. That lead to some issues (#96) as `netsh` translates the data to the os language.

I have rewritten the whole `wifi_hotspot.rs` file to use the Windows API instead. This should be less error prone, but I had to use some unsafe functions and pointers that needed to be freed. After handling those I don't see any memory leaks in my tests, but it may be worth testing that again. Also, it should work with any Windows version that Tauri works on, but I can only test in Windows 10.

Let me know of any question or suggestion.

Closes #96 

Side note: I have removed the `Win32_System_Threading` feature as it doesn't seem to be used anywhere else.

2024-10-10 05:58 UTC, lars-berger requested changes

2024-10-10 05:58 UTC, lars-berger commented on packages/desktop/src/providers/network/wifi_hotspot.rs
> +  fn drop(&mut self) {
Need to wrap in conditional for `windows` compilation

2024-10-10 05:58 UTC, lars-berger commented on packages/desktop/src/providers/network/wifi_hotspot.rs
> +/// Gets wifi ssid and signal stregth using winapi
strength typo

2024-10-10 05:58 UTC, lars-berger commented on packages/desktop/src/providers/network/wifi_hotspot.rs
> +    let ssid = String::from_utf8(ssid_vec).unwrap();
Could we use `.context` here instead of `.unwrap`?

2024-10-11 03:37 UTC, SebasF1349 commented
Fixed requested changes.

2024-10-14 08:18 UTC, merged

2024-10-14 08:18 UTC, lars-berger commented
Perfect!! Thanks a bunch 🙌